CREATE MEMORY TABLE PUBLIC.PORTFOLIO(
    ID INT PRIMARY KEY,
    FOLIONUMBER VARCHAR(255) NOT NULL,
    CLIENTNAME VARCHAR(255) NOT NULL,
    PURCHASEDDATE DATE NOT NULL,
    FUNDNAME VARCHAR(255) NOT NULL,
    OPTION VARCHAR(255),
    INVESTMENTAMOUNT DECIMAL,
    PURCHASENAV DECIMAL,
    UNITSPURCHASED DECIMAL
);


CREATE MEMORY TABLE PUBLIC.FUNDDATA(
    FUND_ID INT PRIMARY KEY,
    FUND_NAME VARCHAR(255) NOT NULL,
    FUND_URL VARCHAR(255) NOT NULL,
    FUND_KEYS VARCHAR(255) NOT NULL
);